In [1]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
## here Estimated salary is continuos figure and so this problem statement is a Regression problem statement

## Preprocess the data
# Drop irrelevant features
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1) # axis=1 for columns

data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [4]:
# here Geography and Gender are categorical features, we need to encode them

# Encode categorical features
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender']) # this will convert Male to 1 and Female to 0



data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [6]:
# label_encoder_geography = LabelEncoder()
# data['Geography'] = label_encoder_geography.fit_transform(data['Geography']) # this will convert France to 0, Germany to 1 and Spain to 2

# here we will not use label encoding for Geography because it will create an ordinal relationship between the categories, which is not true. Instead, we will use one-hot encoding.
# data = pd.get_dummies(data, columns=['Geography'], prefix='Geography')

from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geo = OneHotEncoder() 
geo_encoder = one_hot_encoder_geo.fit_transform(data[['Geography']]) # fit and transform the Geography column
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))

geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [8]:
## divide the dataset into independent and dependent features

x = data.drop('EstimatedSalary',axis = 1)
y = data['EstimatedSalary']

In [9]:
## split data in training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

## Scale the features
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.fit_transform(X_test)

In [10]:
#saving encoders and scalar - one_hot_encoder_geo and label_encoder_gender as pickle file - file in disk, so that we can use this in E2E project

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('one_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)

# saving the scalar of X_train and X_test in pickle format

with open('scalar.pkl','wb') as file:
    pickle.dump(scalar,file)

## Train ANN Regression Problem Statement

In [11]:
## ANN Implementation

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\bharg\myPython\secondSampleProj\myenv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [12]:
## Build our ANN model

## give input and hidden layer 1 with 64 neurons
model = Sequential([
    Dense(64, activation='relu',input_shape=(X_train.shape[1],)), # HL1 connected with input layer
    Dense(32, activation='relu'), # HL2
    Dense(1) # output layer for regression, if no activation fn is given, by default would take linear activation fn
]
)

WARNING:tensorflow:From c:\Users\bharg\myPython\secondSampleProj\myenv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [14]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

#search for keras loss functions in google, to get to know what all loss functions are available for both classification and regression
#problem statements

WARNING:tensorflow:From c:\Users\bharg\myPython\secondSampleProj\myenv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
# Setup the tensorboard so that we can visualize the training logs
import datetime
from  tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [18]:
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True) 
# validation loss and patience = 5 means wait for atleast 5 epochs

In [19]:
### Training the model

history = model.fit(
    X_train,y_train,
    validation_data = (X_test,y_test),
    epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\bharg\myPython\secondSampleProj\myenv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\bharg\myPython\secondSampleProj\myenv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 5ms/step - loss: 100373.1406 - mae: 100373.1406 - val_loss: 98500.8828 - val_mae: 98500.8828
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99579.5859 - mae: 99579.5859 - val_loss: 96909.6172 - val_mae: 96909.6172
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 96828.9531 - mae: 96828.9531 - val_loss: 92894.5078 - val_mae: 92894.5078
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 91476.3047 - mae: 91476.3047 - val_loss: 86270.1484 - val_mae: 86270.1484
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 83734.8516 - mae: 83734.8516 - val_loss: 77812.6172 - val_mae: 77812.6172
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 74710.5938 - mae: 74710.5938 - val_loss: 68982.3828 - val_mae: 68982.3828
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 65914.8984 - mae: 65914.8984 - val_loss: 61329.4492 - val_mae: 61329.4492
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 58947.9531 - mae: 58947.9531 - val_loss: 55891.3203 - val_mae: 55891.3203
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 54368.1797 - mae: 54368.1797 - val_loss: 52830.4844 - val_mae: 52830.4844
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 51915.3867 - mae: 51915.3867 - val_loss: 51457.7070 - val_mae: 51457.7070
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 50898.1836 - mae: 50898.1836 - val_loss: 51046.0312 - val_mae: 51046.0312
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50533.4453 - mae: 50533.4453 - val_loss: 50916.8711 - val_mae: 50916.8711
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50379.9648 - mae: 50379.9648 - val_loss: 50848.2148 - val_mae: 50848.2148
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50292.8516 - mae: 50292.8516 - val_loss: 50799.0898 - val_mae: 50799.0898
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50225.1680 - mae: 50225.1680 - val_loss: 50747.8633 - val_mae: 50747.8633
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50166.5391 - mae: 50166.5391 - val_loss: 50714.7695 - val_mae: 50714.7695
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50117.2695 - mae: 50117.2695 - val_loss: 50672.9297 - val_mae: 50672.9297
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50068.8672 - mae: 50068.8672 - val_loss: 50637.0586 - val_mae: 50637.0586
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50025.6250 - mae: 50025.6250 - val_loss: 50593.8008 - val_mae: 50593.8008
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49989.8945 - mae: 49989.8945 - val_loss: 50559.3359 - val_mae: 50559.3359
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49948.3633 - mae: 49948.3633 - val_loss: 50531.4336 - val_mae: 50531.4336
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49919.5117 - mae: 49919.5117 - val_loss: 50512.0234 - val_mae: 50512.0234
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49891.3711 - mae: 49891.3711 - val_loss: 50489.8594 - val_mae: 50489.8594
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49865.0352 - mae: 49865.0352 - val_loss: 50468.6406 - val_mae: 50468.6406
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49837.4531 - mae: 49837.4531 - val_loss: 50454.7031 - val_mae: 50454.7031
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 49812.3203 - mae: 49812.3203 - val_loss: 50429.2656 - val_mae: 50429.2656
Epoch 27/100
250/250 [==============================] - 1s 4ms/step - loss: 49793.4258 - mae: 49793.4258 - val_loss: 50417.6133 - val_mae: 50417.6133
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49773.0156 - mae: 49773.0156 - val_loss: 50401.6289 - val_mae: 50401.6289
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49753.4531 - mae: 49753.4531 - val_loss: 50394.8047 - val_mae: 50394.8047
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49735.7773 - mae: 49735.7773 - val_loss: 50380.2617 - val_mae: 50380.2617
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49718.8477 - mae: 49718.8477 - val_loss: 50366.5273 - val_mae: 50366.5273
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49701.7617 - mae: 49701.7617 - val_loss: 50360.6562 - val_mae: 50360.6562
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49687.8203 - mae: 49687.8203 - val_loss: 50357.8945 - val_mae: 50357.8945
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49673.3477 - mae: 49673.3477 - val_loss: 50352.0508 - val_mae: 50352.0508
Epoch 35/100
250/250 [==============================] - 1s 4ms/step - loss: 49662.4414 - mae: 49662.4414 - val_loss: 50345.8047 - val_mae: 50345.8047
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49642.9336 - mae: 49642.9336 - val_loss: 50334.2578 - val_mae: 50334.2578
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49633.6953 - mae: 49633.6953 - val_loss: 50319.2422 - val_mae: 50319.2422
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 49621.7188 - mae: 49621.7188 - val_loss: 50311.8125 - val_mae: 50311.8125
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 49610.5977 - mae: 49610.5977 - val_loss: 50309.4727 - val_mae: 50309.4727
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49600.2539 - mae: 49600.2539 - val_loss: 50301.7695 - val_mae: 50301.7695
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49588.1992 - mae: 49588.1992 - val_loss: 50298.0117 - val_mae: 50298.0117
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49577.4023 - mae: 49577.4023 - val_loss: 50295.5195 - val_mae: 50295.5195
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49568.9883 - mae: 49568.9883 - val_loss: 50289.9219 - val_mae: 50289.9219
Epoch 44/100
250/250 [==============================] - 1s 4ms/step - loss: 49565.8086 - mae: 49565.8086 - val_loss: 50292.4961 - val_mae: 50292.4961
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49554.2461 - mae: 49554.2461 - val_loss: 50284.4336 - val_mae: 50284.4336
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49547.4023 - mae: 49547.4023 - val_loss: 50275.2812 - val_mae: 50275.2812
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 49535.9688 - mae: 49535.9688 - val_loss: 50269.2930 - val_mae: 50269.2930
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49529.8945 - mae: 49529.8945 - val_loss: 50261.5547 - val_mae: 50261.5547
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 49520.3438 - mae: 49520.3438 - val_loss: 50263.9023 - val_mae: 50263.9023
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49510.9023 - mae: 49510.9023 - val_loss: 50266.7969 - val_mae: 50266.7969
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49508.0156 - mae: 49508.0156 - val_loss: 50261.5898 - val_mae: 50261.5898
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49498.1211 - mae: 49498.1211 - val_loss: 50266.9883 - val_mae: 50266.9883
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49494.3281 - mae: 49494.3281 - val_loss: 50255.4961 - val_mae: 50255.4961
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49487.4844 - mae: 49487.4844 - val_loss: 50261.2852 - val_mae: 50261.2852
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49479.9648 - mae: 49479.9648 - val_loss: 50267.0078 - val_mae: 50267.0078
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49472.5000 - mae: 49472.5000 - val_loss: 50258.3555 - val_mae: 50258.3555
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49466.5586 - mae: 49466.5586 - val_loss: 50260.6289 - val_mae: 50260.6289
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49462.7539 - mae: 49462.7539 - val_loss: 50260.9844 - val_mae: 50260.9844
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 49459.5938 - mae: 49459.5938 - val_loss: 50272.3516 - val_mae: 50272.3516
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49450.6914 - mae: 49450.6914 - val_loss: 50270.6328 - val_mae: 50270.6328
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 49444.5977 - mae: 49444.5977 - val_loss: 50274.3672 - val_mae: 50274.3672
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 49440.2188 - mae: 49440.2188 - val_loss: 50273.6953 - val_mae: 50273.6953
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 49433.4531 - mae: 49433.4531 - val_loss: 50269.2031 - val_mae: 50269.2031

In [20]:
%load_ext tensorboard

In [22]:

%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 16372), started 0:00:39 ago. (Use '!kill 16372' to kill it.)

In [23]:
## Evaluate model on test data

test_loss, test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE :  {test_mae}')

63/63 [==============================] - 0s 1ms/step - loss: 50255.4961 - mae: 50255.4961
Test MAE :  50255.49609375

In [24]:
model.save('regression_model.h5')

c:\Users\bharg\myPython\secondSampleProj\myenv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(